src/main/java/com/documents/domain/document/User.java
package com.documents.domain.document;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.Date;

@Document(collection = "users")
public class User {

    @Id
    private String id;
    private String firstName;
    private String lastName;

    @Indexed
    private String username;
    private String password;
    private String identificationNumber;
    private int status;
    private int role;
    private Date creationDate;


    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getIdentificationNumber() {
        return this.identificationNumber;
    }

    public void setIdentificationNumber(String identificationNumber) {
        this.identificationNumber = identificationNumber;
    }

    public String getFirstName() {
        if (firstName != null) {
            return firstName.toUpperCase();
        }

        return "";
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName.toUpperCase();
    }

    public String getLastName() {
        if (lastName != null) {
            return lastName.toUpperCase();
        }

        return "";
    }

    public void setLastName(String lastName) {
        this.lastName = lastName.toUpperCase();
    }

    public String getFullName() {
        return this.firstName + " " + this.lastName;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public int getRole() {
        return this.role;
    }

    public void setRole(int role) {
        this.role = role;
    }

    public int getStatus() {
        return this.status;
    }

    public void setStatus(int status) {
        this.status = status;
    }
}

src/main/webapp/WEB-INF/views/common/current-user.jsp
<%@ taglib prefix="tag" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="core" uri="http://java.sun.com/jsp/jstl/core" %>
<div class="current-user">
    <a href="index.html" class="name">
        <%--<img class="avatar" src='<core:url value="/resources/images/avatars/1.jpg" />' />--%>
        <span>
            <core:if test="${not empty currentUser}">
                <core:out value="${currentUser.fullName}" /><br />
                <tag:role-header role="${currentUser.role}" />
            </core:if>
            <i class="fa fa-chevron-down"></i>
        </span>
    </a>
    <ul class="menu">
        <li>
            <a href="/j_spring_security_logout">Salir</a>
        </li>
    </ul>
</div>

src/main/webapp/WEB-INF/views/common/header.jsp
<div id="custom-header">
    <div class="row-fluid">
        <div class="span6 pull-left">
            <h4>Sistema de Gesti&oacute;n Documental v1.0</h4>
        </div>
        <div class="span6 pull-right" style="margin-top:11px">
            Cooperativa de Ahorro y Cr&eacute;dito Andina Ltda.
        </div>
    </div>
</div>

src/main/webapp/WEB-INF/views/common/menu.jsp
<%@ taglib uri="http://www.springframework.org/security/tags" prefix="security" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="core" %>


<security:authorize access="hasRole('ROLE_ADMINISTRATOR')">
    <div class="menu-section">
        <h3>Administrador</h3>
        <ul>
            <li>
                <a href="/users">
                    <i class="ion-person-stalker"></i>
                    <span>Usuarios</span>
                </a>
            </li>
            <li>
                <a href="/mail-sender/compose">
                    <i class="ion-android-mail"></i>
                    <span>Enviar Correo</span>
                </a>
            </li>
        </ul>
    </div>
    <div class="menu-section">
        <h3>Oficial de Cr&eacute;dito</h3>
        <ul>
            <li>
                <a href="/operations">
                    <i class="ion-briefcase"></i>
                    <span>Operaciones</span>
                </a>
            </li>
            <li>
                <a href="/clients">
                    <i class="ion-person-add"></i>
                    <span>Clientes</span>
                </a>
            </li>
            <li>
                <a href="/emails">
                    <i class="ion-archive"></i>
                    <span>Correos Enviados</span>
                </a>
            </li>
            <li>
                <a href="#" data-toggle="sidebar">
                    <i class="ion-gear-b"></i><span>Configuraci&oacute;n</span>
                    <i class="fa fa-chevron-down"></i>
                </a>
                <ul class="submenu">
                    <li><a href="/requirements">Requerimientos</a></li>
                    <li><a href="/credits">Cr&eacute;ditos</a></li>
                    <li><a href="/templates">Plantillas</a></li>
                </ul>
            </li>
            <li>
                <a href='<core:url value="/resources/documents/manual-usuario.pdf" />' target="_blank">
                    <i class="ion-help"></i>
                    <span>Ayuda</span>
                </a>
            </li>
        </ul>
    </div>
</security:authorize>

<security:authorize access="hasRole('ROLE_LOAN_OFFICER')">
    <div class="menu-section">
        <h3>Oficial de Cr&eacute;dito</h3>
        <ul>
            <li>
                <a href="/operations">
                    <i class="ion-briefcase"></i>
                    <span>Operaciones</span>
                </a>
            </li>
            <li>
                <a href='<core:url value="/resources/documents/manual-usuario.pdf" />' target="_blank">
                    <i class="ion-help"></i>
                    <span>Ayuda</span>
                </a>
            </li>
        </ul>
    </div>
</security:authorize>